#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $GTM_DEMO_POSTGRES_USER WITH PASSWORD '$GTM_DEMO_POSTGRES_PASS' CREATEDB;
EOSQL
