---
- hosts: all
  become: yes

  vars:
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: docker
      - name: docker-compose

  pre_tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  tasks:
    - name: Install Pip
      import_role:
        name: geerlingguy.pip

    - name: Install Git
      import_role:
        name: geerlingguy.git

    - name: Install Docker
      import_role:
        name: geerlingguy.docker

    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present

    - name: Add the user "{{ ansible_user }}" to the "docker" group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install postgres for gtm-demo
      import_role:
        name: postgres
      tags: postgres

    - name: Install gtm-demo.ml
      import_role:
        name: gtm-demo
