# Generated by Django 3.1.7 on 2021-02-20 09:52

from django.db import migrations, models
import gtm_demo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoLanding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gtm_id",
                    models.CharField(
                        max_length=15,
                        validators=[gtm_demo.models.validate_gtm_id],
                        verbose_name="ID контейнера GTM",
                    ),
                ),
                (
                    "hashcode",
                    models.SlugField(
                        editable=False,
                        max_length=8,
                        unique=True,
                        verbose_name="Хэш-код",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "демо-лендинг",
                "verbose_name_plural": "демо-лендинги",
            },
        ),
    ]
