# Generated by Django 3.1.7 on 2021-02-22 15:15

from django.db import migrations, models
import gtm_demo.models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demolanding',
            name='gtm_id',
            field=models.CharField(db_index=True, max_length=15, validators=[gtm_demo.models.validate_gtm_id], verbose_name='ID контейнера GTM'),
        ),
    ]
